;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	helm-confirm-and-exit-minibuffer
	isearch-repeat-backward
	sp--self-insert-command
	sp-delete-char
	sp-kill-hybrid-sexp
	sp-kill-word
	))

(setq mc/cmds-to-run-once
      '(
	sp-backward-delete-char
	))
